version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    working_dir: /app
    command: ["/wait-for-it.sh", "db:5432", "--", "pytest"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - flight-network

  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=flight_user
      - POSTGRES_PASSWORD=flight_pass
      - POSTGRES_DB=flight_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - flight-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U flight_user -d flight_db"]
      interval: 5s
      timeout: 5s
      retries: 5

networks:
  flight-network:
    driver: bridge

volumes:
  postgres_data: